const products = [
  {
    _id: '1',
    name: 'Elmo',
    image: '/images/Elmo.jpg',
    description: 'Elmo from sessame street, a puppet like Stuffed toy',
    price: 99.99,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: '2',
    name: 'Luffy',
    image: '/images/Luffy.jpg',
    description: 'Stuffed toy Luffy from anime one piece',
    price: 149.99,
    countInStock: 7,
    rating: 4.0,
    numReviews: 8,
  },
  {
    _id: '3',
    name: 'Mickey Mouse',
    image: '/images/MickeyMouse.jpg',
    description: 'Mickey Mouse stuffed toy, a disney character',
    price: 199.99,
    countInStock: 5,
    rating: 3,
    numReviews: 12,
  },
  {
    _id: '4',
    name: 'Pichu',
    image: '/images/Pichu.jpg',
    description: 'Pichu stuffed toy from the anime and game pokemon',
    price: 299.99,
    countInStock: 11,
    rating: 5,
    numReviews: 12,
  },
  {
    _id: '5',
    name: 'Spongebob',
    image: '/images/Spongebob.jpg',
    description: 'Spongebob stuffed toy from the cartoon Spongebob Squarepants',
    price: 199.99,
    countInStock: 7,
    rating: 3.5,
    numReviews: 10,
  },
  {
    _id: '6',
    name: 'Stitch',
    image: '/images/Stitch.jpg',
    description: 'Stitch stuffed toy from the cartoon Lilo and Stitch',
    price: 149.99,
    countInStock: 0,
    rating: 4,
    numReviews: 12,
  },
]
